ENVIRONMENT="dev"

PREFIX="hdb-eventdriven"

ACCOUNT_ID="$(aws sts get-caller-identity \
    --query Account \
    --output text)"

REGION="$(aws configure get region)"

ARTIFACT_BUCKET="${PREFIX}-${ACCOUNT_ID}"

RAW_BUCKET="${PREFIX}-${ENVIRONMENT}-raw-${ACCOUNT_ID}"

BRONZE_BUCKET="${PREFIX}-${ENVIRONMENT}-bronze-${ACCOUNT_ID}"

SILVER_BUCKET="${PREFIX}-${ENVIRONMENT}-silver-${ACCOUNT_ID}"

GOLD_BUCKET="${PREFIX}-${ENVIRONMENT}-gold-${ACCOUNT_ID}"

METADATA_BUCKET="${PREFIX}-${ENVIRONMENT}-metadata-${ACCOUNT_ID}"

GLUE_DB_NAME="${PREFIX}_${ENVIRONMENT}_db"

ATHENA_WORKGROUP="${PREFIX}-${ENVIRONMENT}-wg"